# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4cb7288d441afbdfe51bc617c10dfd257694a7496bb8e67fd67a2256c7fe8ce661334486c4b9561f80c74330415df2c96e61e948a8c2e65bc7979f0b141d97dc

test:
  secret_key_base: 0dd74f9a8bc8d73764479b9a8dd00cf2680d32bf206118c89bf27a4bc9f235178ab814117b7cbf5750440fd93dc573b625cb17702d13acaae7216fee6516030b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
